feat(vuepress): add client type export
vuepress/core pull request #1460
Opened 2023-12-29 14:08 UTC by Mister-Hope

2023-12-29 15:33 UTC, meteorlxy requested changes

2023-12-29 15:33 UTC, meteorlxy commented on packages/vuepress/package.json
> +    "./client-types": "./dist/client-types.js",
Where's the client-types file? 😅

2023-12-29 20:17 UTC, Mister-Hope commented on packages/vuepress/package.json
> +    "./client-types": "./dist/client-types.js",
oh the dts file, forget to add that

2023-12-31 17:14 UTC, meteorlxy approved these changes

2023-12-31 17:15 UTC, merged