fix(markdown): fix linksPlugin parsing query and wrong absolute link
vuepress/core pull request #1537
Opened 2024-04-11 08:48 UTC by Mister-Hope

2024-05-13 10:17 UTC, meteorlxy commented on packages/client/src/components/AutoLink.ts
> +   * 项目文字
remove zh comments

2024-05-14 05:14 UTC, meteorlxy commented
Need to update test cases

2024-05-14 05:14 UTC, meteorlxy requested changes
Need to update test cases

2024-05-14 09:02 UTC, Mister-Hope commented
What test cases is not update? This PR is not introducing any new functions, while I already updated existing ones.

2024-05-16 00:35 UTC, meteorlxy approved these changes

2024-05-16 00:35 UTC, merged