feat(client): add `onContentUpdated` hooks
vuepress/core pull request #1620
Opened 2024-12-06 06:51 UTC by pengzhanbo

### Before submitting the PR, please make sure you do the following 

- [x] Read the [Contributing Guidelines](https://github.com/vuepress/core/blob/main/CONTRIBUTING.md).
- [x] Provide a description in this PR that addresses **what** the PR is solving. If this PR is going to solve an existing issue, please reference the issue (e.g. `close #123`).

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Other

### Description

When the markdown content changes, using the built-in Vue lifecycle hooks does not work well, so the `onContentUpdated` hook has been added to properly listen for changes in the content.

This applies to scenarios such as `medium-zoom` or `photo-swipe` that require reinitialization when the page content changes.

2024-12-06 10:32 UTC, Mister-Hope approved these changes

2024-12-06 10:32 UTC, Mister-Hope commented
uepress/docs also needs a PR

2024-12-06 14:03 UTC, pengzhanbo commented
> uepress/docs also needs a PR

<https://github.com/vuepress/docs/pull/44>

2024-12-11 06:43 UTC, meteorlxy requested changes
e2e tests are required

2024-12-15 14:20 UTC, pengzhanbo commented
@meteorlxy @Mister-Hope 
I have rewritten this PR and added relevant e2e tests referencing hmr, but it is not working properly in vite. Can you help me resolve this?

2025-02-21 05:51 UTC, meteorlxy commented on packages/client/src/composables/onContentUpdated.ts
> +export function runCallbacks(reason: ContentUpdatedReason): void {
- Should use arrow function to keep consistent with other functions
- The name could be improved.
- Add js docs. Maybe a `@internal` mark is better.

2025-02-21 05:52 UTC, meteorlxy commented on packages/client/src/composables/index.ts
> +export * from './onContentUpdated.js'
Reorder the exports in alphabetically

2025-02-23 15:22 UTC, meteorlxy approved these changes

2025-02-23 15:28 UTC, merged